### ISSUE TITLE
Cannot modify header information

### ISSUE THREAD

**Issue by ghost** [Uranium235/pluck-cms-contactform_captcha#1]
Hello

I want to use your script and get the following message in my image:
Warning: Can not modify header information - headers already sent by (data/modules/contactform_captcha/contactform_captcha.site.php on line 20)

Can you help me

With Friendly Greeting André

**Comment by Uranium235** [comment]
Hi,

This error is given when trying to modify http headers and there has already been content data sent to the client.

I am a little confused by what you mean by "message in my image"? Are you saying that instead of a valid .png file there is this error message inside? Because that should not be the case as contactform_captcha.site.php is not loaded when creating the image.

My guess is that your server and/or php environment is not configured properly with respect to timezone settings and php outputs an error message when using gmdate(), even if it is not visible in the browser. Look at the source code for the generated html (from within your browser: view source) if there are any error messages at the beginning of the file before the actual html file begins.

try running this and see if you get any error messages:

``` php
<?php
date_default_timezone_set('UTC'); // this is set in pluck's data/inc/security.php line 32
echo gmdate('r'); // line 20 in contactform_captcha.site.php
```

EDIT:
Is that the complete error message? Shouldn't there be sth. like this: "output started at"?
If there is, that is the problem. [Hints](https://www.arclab.com/en/webformbuilder/php-warning-cannot-modify-header-information-headers-already-sent.html)

**Comment by ghost** [comment]
Hello

The annex to the time zone of the server and i also put in the annex next to the pluck but at the moment I still have the same error message?

What can I do?

M.v.g. André

Complete error 
<code>
Warning: Cannot modify header information - headers already sent by (output started at /home/dshopyou/domains/3dshop4you.nl/public_html/data/themes/default/theme.php:4) in /home/dshopyou/domains/3dshop4you.nl/public_html/data/modules/contactform_captcha/contactform_captcha.site.php on line 20
</code>
<code>
Warning: Cannot modify header information - headers already sent by (output started at /home/dshopyou/domains/3dshop4you.nl/public_html/data/themes/default/theme.php:4) in /home/dshopyou/domains/3dshop4you.nl/public_html/data/modules/contactform_captcha/contactform_captcha.site.php on line 21
</code>
<code>
Warning: Cannot modify header information - headers already sent by (output started at /home/dshopyou/domains/3dshop4you.nl/public_html/data/themes/default/theme.php:4) in /home/dshopyou/domains/3dshop4you.nl/public_html/data/modules/contactform_captcha/contactform_captcha.site.php on line 22
<code>
Warning: Cannot modify header information - headers already sent by (output started at /home/dshopyou/domains/3dshop4you.nl/public_html/data/themes/default/theme.php:4) in /home/dshopyou/domains/3dshop4you.nl/public_html/data/modules/contactform_captcha/contactform_captcha.site.php on line 23
</code>
<code>
Warning: Cannot modify header information - headers already sent by (output started at /home/dshopyou/domains/3dshop4you.nl/public_html/data/themes/default/theme.php:4) in /home/dshopyou/domains/3dshop4you.nl/public_html/data/modules/contactform_captcha/contactform_captcha.site.php on line 24
</code>
<code>
Warning: Cannot modify header information - headers already sent by (output started at /home/dshopyou/domains/3dshop4you.nl/public_html/data/themes/default/theme.php:4) in /home/dshopyou/domains/3dshop4you.nl/public_html/data/modules/contactform_captcha/contactform_captcha.site.php on line 25
</code>
<code>
Warning: Cannot modify header information - headers already sent by (output started at /home/dshopyou/domains/3dshop4you.nl/public_html/data/themes/default/theme.php:4) in /home/dshopyou/domains/3dshop4you.nl/public_html/data/modules/contactform_captcha/contactform_captcha.site.php on line 26
</code>

**Comment by Uranium235** [comment]
Are you actually using pluck cms or are you trying to use the module elsewhere?

The order in which the template (`theme.php`) is included and the function `contactform_captcha_site_theme` (`contactform_captcha.site.php`) are run is very important.

The function needs to be called before the theme is run. It modifies the http headers to instruct browsers and proxies to not cache the file. That is necessary so that you get a new CAPTCHA with every page (re)load.
If you are trying to use the CAPTCHA module outside of pluck, you should make sure that the instructions inside the function are run before any output by the template / theme.
If you want to include the module directly into a file, that would be just after / instead of `defined('IN_PLUCK') or exit('Access denied!');` in line 3 in the default theme.php.

pluck should ensure that in the index.php in line 90 to 99

``` php
//Allow modules to manipulate theme
$page_theme = THEME;
run_hook('site_theme', array(&$page_theme));

//Allow modules to manipulate theme-filename
$page_theme_file = 'theme';
run_hook('site_theme_file', array(&$page_theme_file));

//Now, include the theme
include_once('data/themes/'.$page_theme.'/'.$page_theme_file.'.php');
```

The line `run_hook('site_theme'...` calls the modules `contactform_captcha_site_theme` function before the `theme.php` is is included at the very end.

I don't see any way right now how line 4 in `theme.php` could start any output before the module function is run with a standard pluck `index.php`.

P.S.
I added a check to the function to only actually modify the headers if the contact from is included in a page. But that will not fix your problem though...

**Comment by ghost** [comment]
Hello

I now use the pluck_cms 4.7.3 makes some out
This is the standard version that is downloaded from this page https://github.com/pluck-cms/pluck/releases otherwise I would not know where I need to change what you are told

this code i have

//Allow modules to manipulate theme
$page_theme = THEME;
run_hook('site_theme', array(&$page_theme));

//Allow modules to manipulate theme-filename
$page_theme_file = 'theme';
run_hook('site_theme_file', array(&$page_theme_file));

//Now, include the theme
include_once('data/themes/'.$page_theme.'/'.$page_theme_file.'.php');

M.v.g.

**Comment by Uranium235** [comment]
I found the problem.

The reason why nobody else has really noticed it yet is that warning messages are usually suppressed in production environments.

`run_hook('site_theme',...` is called twice. Once in `index.php` and then again via `theme_meta()` in `theme.php`.

I guess that is because the `THEME` constant does not get (/ cannot be) redefined when modules change the theme and `theme_meta()` needs to let modules change the default theme again to determine the correct theme.

The reason why I change the http headers in `..._site_theme()` - even though I do not actually care about the theme in that function - is, that it there is no dedicated hook for such things in pluck and it gets called before any output is done.

I have changed that to use the `site_theme_file` hook now. That is only called once as far as I can tell. I also included a check to not set the headers again in case it does get called again by e.g. some other module I don't know about.

This should fix your problem. You need to download the module from my repository as the fork in pluck-cms is not up-to-date yet.

**Comment by ghost** [comment]
Hello

Thanks very much for the help I have this downloaded zip pluck-cms contactform_captcha master and also installed in this folder, and when he was not working.
I adapted this contactform_captcha and now it works fine the folder?

What is good the first or the last?

M.v.g.

**Comment by Uranium235** [comment]
Since my changes have been merged by now, both work.
Make sure you have v1.2.
The version can be found inside individual php files at the top or in the README file at the bottom.
